sudo: false

language: rust

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

os:
  - linux
  - osx

script:
  - cargo build --verbose
  - cargo run
  - cargo test
